# Generated by Django 4.2.4 on 2023-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='make_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, help_text='Use comma separated value', null=True),
        ),
    ]
